name: Github Actions - API IMAGENS

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Use .env file
        uses: actions/setup-node@v3
        with:
          node-version: 18
          env-file: ${{ secrets.ENV_FILE }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
