name: Github Actions - API IMAGENS
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_PORT: ${{secrets.APP_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      S3_URL: ${{secrets.S3_URL}}
      S3_KEY: ${{secrets.S3_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup dotenv
        uses: actions/setup-dotenv@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
